CREATE DATABASE proleague;
USE proleague;

CREATE TABLE users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(50) UNIQUE NOT NULL,
  email VARCHAR(100) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
DELETE FROM users WHERE id > 0;


select * from users;

SET SQL_SAFE_UPDATES = 0;
DELETE FROM users;
SET SQL_SAFE_UPDATES = 1; 


CREATE USER 'proleague'@'localhost' IDENTIFIED BY '123456';
GRANT ALL PRIVILEGES ON proleague.* TO 'proleague'@'localhost';
FLUSH PRIVILEGES;